### ISSUE TITLE
Feature : Automatically load src/app or /app || Improving intuitiveness

### ISSUE THREAD

**Issue by damien-schneider** [oslabs-beta/Next-Nav#35]
When I first used it, it wasn't very intuitive to have to load a path,

It might be interesting to load src/app or /app by default depending on the tree.

Or (if the first solution is too complicated), we could also make the button more visual for the first use.

PS: Thanks for the tool, it's really nice!

**Comment by jequerubin** [comment]
Hey Damien!

Thanks for using our tool, glad you found it useful. We appreciate the feedback and are discussing a more permanent solution to the intuitiveness surrounding the import process. However, for now, we're going to implement a small fix that will render the import box on load so that it is more clear for our users. Again, thanks for the suggestion!

**Comment by yannxaver** [comment]
Agreed that automatically checking some default paths would be very useful. Besides that, it should remember the path that was set when closing and reopening the extension.

**Comment by nathanpeel** [comment]
This feature has now been implemented. If you use the normal src/app file structure, your tree will load automatically when opening the extension. Otherwise, you must still enter the file path into the import field. We are considering implementing a feature to remember file paths for future updates, but the main functionality of this issue has been implemented. Thank you for the suggestion. We appreciate the support and feedback!

**Comment by damien-schneider** [comment]
> This feature has now been implemented. If you use the normal src/app file structure, your tree will load automatically when opening the extension. Otherwise, you must still enter the file path into the import field. We are considering implementing a feature to remember file paths for future updates, but the main functionality of this issue has been implemented. Thank you for the suggestion. We appreciate the support and feedback!

This is really cool, thanks !!
